name: Stats

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: '0 0 * * *' #Se ejecuta todos los días a las 00:00 horas

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Run Script
        run: node ./works/first_work.js

      - name: Commit and Push Changes
        uses: stefanzwaifel/git-auto-comit-action@v5
        with:
          commit_message: 'ci(message): first action'
          commit_user_name: Pool [GitHub Actions]
          commit_user_email: pllerena@funciton.com
